### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by PhilippeRT** [stefanogualdi/grails-ckeditor#13]
Hi all,

I install the plug-in in a grails 2.1.5 application, and the .js files does not load, except ckeditor.js.
The issue is in org.gualdi.grails.plugins.ckeditor.utils.PluginUtils, the pluginManager in the Holders class does not reference the plugin.

I resolve this by replacing
    String pluginVersion = Holders.pluginManager.getGrailsPlugin(pluginName)?.version
which give null
by
String pluginVersion = Holders.applicationContext.getBean('pluginManager').getGrailsPlugin(pluginName)?.version

Now it works.

**Comment by jdgiotta** [comment]
Same issue.

**Comment by stefanogualdi** [comment]
Closed with PR from John D Giotta. Thank you.
