### ISSUE TITLE
How to add plugins for CKEditor

### ISSUE THREAD

**Issue by dongxuwang** [stefanogualdi/grails-ckeditor#27]
For example, http://ckeditor.com/addon/wordcount

**Comment by stefanogualdi** [comment]
You have to use the external configuration.

in application.yml add:
```
ckeditor:
  config: "/ckeditor/ckconfig.js"  
```

create the file ```ckconfig.js``` under ```/src/main/resources/public/ckeditor```

with the following content:

```
CKEDITOR.plugins.addExternal('wordcount', '/ckeditor/plugins/wordcount/');
CKEDITOR.plugins.addExternal('notification', '/ckeditor/plugins/notification/');
CKEDITOR.editorConfig = function( config )
{
  config.extraPlugins = 'wordcount,notification';
};
```
copy the plugins under ```/src/main/resources/public/ckeditor/plugins```

**Comment by dongxuwang** [comment]
Pretty cool, thanks heaps.
