### ISSUE TITLE
copy/paste not working in IE11

### ISSUE THREAD

**Issue by avinashkk** [stefanogualdi/grails-ckeditor#33]
I am upgrading the ckeditor to version  4.5.4.0 and having problems getting the copy/paste work on IE11. I need help to know how to use the plugins and configure them in config.js to make it work. Any help will be great.

I am usig the below code to enable the plugins - 
config.extraPlugins = 'clipboard,dialog,dialogui,pastefromword,pastetext';

**Comment by stefanogualdi** [comment]
Please, take a look here: https://github.com/stefanogualdi/grails-ckeditor/issues/27
